# Generated by Django 5.0 on 2026-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0015_alter_heroslider_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='enable_3d_overlay',
            field=models.BooleanField(default=False, help_text='Overlay an interactive 3D scene on this banner.'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='threejs_intensity',
            field=models.FloatField(default=1.0, help_text='Opacity/Brightness of the 3D effect.'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='threejs_model_path',
            field=models.CharField(blank=True, help_text='Path to GLTF/GLB model in static files.', max_length=500, null=True),
        ),
    ]
