# Generated by Django 5.0 on 2026-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_client_image_alt_sitesettings_facebook_pixel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='layout_mode',
            field=models.CharField(choices=[('classic', 'Classic (Centered)'), ('bento', 'Bento Grid (Modern/21st.dev)'), ('floating', 'Floating Cards')], default='bento', max_length=20),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='motion_intensity',
            field=models.CharField(choices=[('low', 'Subtle (Professional)'), ('medium', 'Expressive (Standard)'), ('high', 'Dynamic (Playful)'), ('none', 'None (Static)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='theme_style',
            field=models.CharField(choices=[('glass', 'Glassmorphism (Premium)'), ('dark', 'Luxury Dark (Night Mode)'), ('minimal', 'Minimalist White (Clean)'), ('neon', 'Neon Accent (Modern)')], default='glass', max_length=20),
        ),
    ]
