# Generated by Django 5.0 on 2026-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_designsettings_layout_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='layout_mode',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='motion_intensity',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='theme_style',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_counters_subtitle',
            field=models.TextField(blank=True, default='Quantifying our commitment to excellence and global reach.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_counters_title',
            field=models.CharField(default='Our <span class="text-primary">Impact</span> in Numbers', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_counters',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Counters'),
        ),
    ]
