# Generated by Django 5.0 on 2026-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_sitesettings_admin_notification_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='admin_notification_email',
        ),
    ]
