# Generated by Django 6.0.3 on 2026-05-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_sitesettings_admin_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='site_scale',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Global site scale factor (e.g. 0.8 = 80% size at 100% browser zoom)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='accent_glow_color',
            field=models.CharField(default='#415A77', help_text='Accent Blue for highlights.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='border_color',
            field=models.CharField(default='#415A77', help_text='Dividers, card borders.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='button_radius',
            field=models.CharField(default='9999px', help_text='e.g. 4px (Subtle), 9999px (Pill/Full)', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='card_bg_color',
            field=models.CharField(default='#1B263B', help_text='Card/Container background (Navy).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='card_radius',
            field=models.CharField(default='12px', help_text='e.g. 12px, 0.75rem', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='container_radius',
            field=models.CharField(default='12px', help_text='e.g. 12px, 1rem', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font_main',
            field=models.CharField(choices=[("'Montserrat', sans-serif", 'Montserrat (Bold/Modern)'), ("'Outfit', sans-serif", 'Outfit (Clean/Modern)'), ("'DM Sans', sans-serif", 'DM Sans (Modern/Clean)'), ("'Plus Jakarta Sans', sans-serif", 'Jakarta (High-tech)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Luxury/Serif)')], default="'Open Sans', sans-serif", max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font_secondary',
            field=models.CharField(choices=[("'Montserrat', sans-serif", 'Montserrat (Bold/Modern)'), ("'Outfit', sans-serif", 'Outfit (Clean/Modern)'), ("'DM Sans', sans-serif", 'DM Sans (Modern/Clean)'), ("'Plus Jakarta Sans', sans-serif", 'Jakarta (High-tech)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Luxury/Serif)')], default="'Montserrat', sans-serif", max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_bg_color',
            field=models.CharField(default='#000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_text_color',
            field=models.CharField(default='#E0E1DD', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='header_bg_color',
            field=models.CharField(default='#0D1B2A', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='header_text_color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='image_radius',
            field=models.CharField(default='12px', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='primary_color',
            field=models.CharField(default='#0D1B2A', help_text='Primary Brand Color (Deep Dark Blue).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='secondary_color',
            field=models.CharField(default='#1B263B', help_text='Secondary / Darker Blue.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='surface_bg_color',
            field=models.CharField(default='#0D1B2A', help_text='Main site background (Dark Blue).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='text_primary_color',
            field=models.CharField(default='#E0E1DD', help_text='Main text color (Light Gray/White).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='text_secondary_color',
            field=models.CharField(default='#778DA9', help_text='Muted text/labels.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='text_white_color',
            field=models.CharField(default='#FFFFFF', help_text='Pure white text.', max_length=50),
        ),
    ]
