# Generated by Django 5.0 on 2026-05-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_designsettings_layout_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='hp_categories_badge',
            field=models.CharField(blank=True, default='Discover Excellence', max_length=100),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_categories_subtitle',
            field=models.TextField(blank=True, default='Browse our extensive range of high-performance products, curated to meet the most demanding standards.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_collections_badge',
            field=models.CharField(blank=True, default='Curated Theme', max_length=100),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_latest_products_badge',
            field=models.CharField(blank=True, default='The Premium Standard', max_length=100),
        ),
    ]
