# Generated by Django 6.0.3 on 2026-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_site_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='font_accent',
            field=models.CharField(choices=[("'Montserrat', sans-serif", 'Montserrat (Primary UI Font)'), ("'Inter', sans-serif", 'Inter (Clean UI Alternative)'), ("'Oswald', sans-serif", 'Oswald (Condensed Display Headlines)'), ("'Playfair Display', serif", 'Playfair Display (Premium Serif - Accent/Brand)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Elegant Serif)'), ("'Anton', sans-serif", 'Anton (Bold Condensed)')], default="'Playfair Display', serif", help_text='Premium serif for logo, brand name, and accent sections', max_length=100),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font_main',
            field=models.CharField(choices=[("'Montserrat', sans-serif", 'Montserrat (Primary UI Font)'), ("'Inter', sans-serif", 'Inter (Clean UI Alternative)'), ("'Oswald', sans-serif", 'Oswald (Condensed Display Headlines)'), ("'Playfair Display', serif", 'Playfair Display (Premium Serif - Accent/Brand)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Elegant Serif)'), ("'Anton', sans-serif", 'Anton (Bold Condensed)')], default="'Montserrat', sans-serif", help_text='Primary font for body text, buttons, navigation', max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font_secondary',
            field=models.CharField(choices=[("'Montserrat', sans-serif", 'Montserrat (Primary UI Font)'), ("'Inter', sans-serif", 'Inter (Clean UI Alternative)'), ("'Oswald', sans-serif", 'Oswald (Condensed Display Headlines)'), ("'Playfair Display', serif", 'Playfair Display (Premium Serif - Accent/Brand)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Elegant Serif)'), ("'Anton', sans-serif", 'Anton (Bold Condensed)')], default="'Oswald', sans-serif", help_text='Display font for major headlines and hero titles', max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='site_scale',
            field=models.DecimalField(decimal_places=2, default=0.9, help_text='Global site scale factor (e.g. 0.9 = 90% size at 100% browser zoom)', max_digits=3),
        ),
    ]
