# Generated by Django 5.0 on 2026-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_designsettings_hp_categories_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='enable_custom_cursor',
            field=models.BooleanField(default=True, help_text='Sleek magnetic follower cursor.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='enable_magnetic_hover',
            field=models.BooleanField(default=True, help_text='Buttons and icons pull the cursor towards them.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='enable_page_transitions',
            field=models.BooleanField(default=True, help_text='Smooth fade/slide between pages.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hero_3d_effect',
            field=models.CharField(choices=[('none', 'None'), ('particles', 'Particle Field'), ('fluid', 'Fluid Geometry'), ('floating_products', 'Floating Product Icons'), ('glass_shard', 'Glass Shards')], default='fluid', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='ui_theme_variant',
            field=models.CharField(choices=[('standard', 'Standard Professional'), ('luxury_dark', 'Luxury Midnight (Glassmorphism)'), ('high_tech', 'High-Tech (Glow/Neon)'), ('minimal_art', 'Minimal Artistic')], default='luxury_dark', max_length=50),
        ),
    ]
