# Generated by Django 6.0.3 on 2026-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_designsettings_enable_custom_cursor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='accent_glow_color',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='enable_ambient_glow',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='enable_glassmorphism',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='enable_neumorphism',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='font_secondary',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='font_heading',
            field=models.CharField(choices=[("'Inter', sans-serif", 'Inter (Clean UI - Primary)'), ("'Montserrat', sans-serif", 'Montserrat (Versatile UI)'), ("'Poppins', sans-serif", 'Poppins (Modern Geometric)'), ("'Roboto', sans-serif", 'Roboto (Material Design)'), ("'Open Sans', sans-serif", 'Open Sans (Highly Readable)'), ("'Oswald', sans-serif", 'Oswald (Condensed Display)'), ("'Playfair Display', serif", 'Playfair Display (Premium Serif)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Elegant Serif)')], default="'Montserrat', sans-serif", help_text='Display font for headings and major titles', max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='border_color',
            field=models.CharField(default='#e5e5e5', help_text='Dividers, card borders.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='button_radius',
            field=models.CharField(default='4px', help_text='e.g. 4px (Subtle), 9999px (Pill)', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='card_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Card/Container background.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='card_radius',
            field=models.CharField(default='8px', help_text='e.g. 8px for cards', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='cart_page_title',
            field=models.CharField(default='Your <span class="accent">Cart</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='checkout_page_title',
            field=models.CharField(default='Secure <span class="accent">Checkout</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='contact_page_title',
            field=models.CharField(default='Contact <span class="accent">Us</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='container_radius',
            field=models.CharField(default='8px', help_text='e.g. 8px, 0.5rem for main containers', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font_accent',
            field=models.CharField(choices=[("'Inter', sans-serif", 'Inter (Clean UI - Primary)'), ("'Montserrat', sans-serif", 'Montserrat (Versatile UI)'), ("'Poppins', sans-serif", 'Poppins (Modern Geometric)'), ("'Roboto', sans-serif", 'Roboto (Material Design)'), ("'Open Sans', sans-serif", 'Open Sans (Highly Readable)'), ("'Oswald', sans-serif", 'Oswald (Condensed Display)'), ("'Playfair Display', serif", 'Playfair Display (Premium Serif)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Elegant Serif)')], default="'Playfair Display', serif", help_text='Premium serif for logo, brand name, and accent sections', max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font_main',
            field=models.CharField(choices=[("'Inter', sans-serif", 'Inter (Clean UI - Primary)'), ("'Montserrat', sans-serif", 'Montserrat (Versatile UI)'), ("'Poppins', sans-serif", 'Poppins (Modern Geometric)'), ("'Roboto', sans-serif", 'Roboto (Material Design)'), ("'Open Sans', sans-serif", 'Open Sans (Highly Readable)'), ("'Oswald', sans-serif", 'Oswald (Condensed Display)'), ("'Playfair Display', serif", 'Playfair Display (Premium Serif)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Elegant Serif)')], default="'Inter', sans-serif", help_text='Primary font for body text, buttons, navigation', max_length=100),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_bg_color',
            field=models.CharField(default='#1a1a1a', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_text_color',
            field=models.CharField(default='#f5f5f5', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='global_animation_type',
            field=models.CharField(choices=[('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('zoom-in', 'Zoom In'), ('slide-left', 'Slide Left'), ('none', 'No Animation')], default='fade-up', max_length=20),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='header_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='header_text_color',
            field=models.CharField(default='#1a1a1a', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_categories_title',
            field=models.CharField(default='Shop by <span class="accent">Category</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_collections_subtitle',
            field=models.TextField(blank=True, default='Handpicked selection of premium floral arrangements.'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_collections_title',
            field=models.CharField(default='Exclusive <span class="accent">Collections</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_gallery_title',
            field=models.CharField(default='Our <span class="accent">Gallery</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_hero_subtitle',
            field=models.TextField(blank=True, default='Discover elegant floral arrangements for every occasion.'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_hero_title',
            field=models.CharField(default='Premium <span class="accent">Flowers</span> & Gifts', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_latest_products_subtitle',
            field=models.TextField(blank=True, default='Discover our newest floral creations.'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_latest_products_title',
            field=models.CharField(default='Latest <span class="accent">Products</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_partners_title',
            field=models.CharField(default='Our Partners', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_services_title',
            field=models.CharField(default='Why Choose Us', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_social_title',
            field=models.CharField(default='Follow Us', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_testimonials_title',
            field=models.CharField(default='What Our Customers Say', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='image_radius',
            field=models.CharField(default='8px', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='orders_page_title',
            field=models.CharField(default='Order <span class="accent">History</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='primary_color',
            field=models.CharField(default='#114084', help_text='Primary Brand Color (Deep Blue).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='profile_page_title',
            field=models.CharField(default='My <span class="accent">Account</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='search_page_title',
            field=models.CharField(default='Search <span class="accent">Results</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='secondary_color',
            field=models.CharField(default='#1a5cb8', help_text='Secondary Blue for hover states.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='site_scale',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Global site scale factor (e.g. 0.9 = 90% size at 100% browser zoom)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='surface_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Main site background (Clean White).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='text_primary_color',
            field=models.CharField(default='#1a1a1a', help_text='Main text color (Near Black).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='text_secondary_color',
            field=models.CharField(default='#666666', help_text='Muted text/labels.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='wishlist_page_title',
            field=models.CharField(default='My <span class="accent">Wishlist</span>', max_length=255),
        ),
    ]
