# Generated by Django 5.0 on 2026-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_promo_banners',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='2-column photo banner grid (Vase / Basket category entry points).', verbose_name='Promo Banner Grid'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_trust_strip',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='White horizontal 3-pillar trust bar below hero (Delivery, Payment, Support).', verbose_name='Trust Strip'),
        ),
    ]
