# Generated by Django 6.0.3 on 2026-05-27 23:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_hp_visibility_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Managed via RichText in Website Settings.', verbose_name='Privacy Policy Content'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Managed via RichText in Website Settings.', verbose_name='Terms and Conditions Content'),
        ),
    ]
