# Generated by Django 5.0 on 2026-05-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_pagehero_meta_description_pagehero_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('about', 'About Us'), ('products', 'Products'), ('services', 'Services'), ('gallery', 'Gallery'), ('stores', 'Stores'), ('blog', 'Blog'), ('brands', 'Brands'), ('contact', 'Contact Us')], max_length=20, unique=True),
        ),
    ]
