# Generated by Django 6.0.3 on 2026-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_heroslide_homepagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='announcement_text',
            field=models.CharField(default='🌸 \xa0 Free delivery on orders over 200 AED \xa0|\xa0 Same-day delivery available \xa0🌸', help_text='Text shown in the top announcement bar. Leave blank to use the dynamic Announcement Bar records.', max_length=400),
        ),
    ]
