# Generated by Django 6.0.3 on 2026-05-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_homepagesettings_announcement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='pages.aboutus'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='pages.aboutus'),
        ),
        migrations.AddField(
            model_name='missionvision',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_vision_items', to='pages.aboutus'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='pages.aboutus'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='pages.aboutus'),
        ),
        migrations.AddField(
            model_name='whyuscard',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_us_cards', to='pages.aboutus'),
        ),
    ]
