# Generated by Django 5.0 on 2026-05-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_counter_about_us_galleryitem_about_us_and_more'),
        ('products', '0053_alter_product_created_at_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='exclusive_products',
            field=models.ManyToManyField(blank=True, help_text='Select products to manually showcase in the Exclusive Products / Latest Arrivals section.', related_name='homepage_exclusive_settings', to='products.product'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='onsale_products',
            field=models.ManyToManyField(blank=True, help_text='Select products to manually showcase in the On Sale Now section.', related_name='homepage_onsale_settings', to='products.product'),
        ),
    ]
