# Generated by Django 6.0.3 on 2026-06-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_homepagesettings_exclusive_products_and_more'),
    ]

    operations = [
        # Drop columns added in 0020_homepage_settings_modernize
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_eyebrow CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_title_html CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_badge_text CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_stat_1_number CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_stat_1_label CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_stat_2_number CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_stat_2_label CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_stat_3_number CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS hero_stat_3_label CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS show_features_strip CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_1_title CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_1_desc CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_1_icon CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_2_title CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_2_desc CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_2_icon CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_3_title CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_3_desc CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_3_icon CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_4_title CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_4_desc CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS feature_4_icon CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS show_categories_section CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS categories_title CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS categories_subtitle CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS categories_btn_text CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS categories_btn_link CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS show_featured_section CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS featured_btn_text CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS featured_btn_link CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS show_testimonial_section CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS testimonial_text CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS testimonial_author_name CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS testimonial_author_role CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS testimonial_author_avatar_initials CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS show_cta_section CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS cta_title CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS cta_subtitle CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS cta_primary_btn_text CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS cta_primary_btn_link CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS cta_secondary_btn_text CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='ALTER TABLE pages_homepagesettings DROP COLUMN IF EXISTS cta_secondary_btn_link CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),

        # Add the old fields
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_eyebrow',
            field=models.CharField(default='Luxury Floral Atelier', help_text='Small uppercase label above the hero title.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_title_line1',
            field=models.CharField(default='Flowers that', help_text='First line of the large hero title.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_title_em',
            field=models.CharField(default='speak', help_text='Italic/rose-coloured word in the middle of the hero title.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_title_line2',
            field=models.CharField(default='your heart', help_text='Third line of the large hero title.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_tag_label',
            field=models.CharField(default="Today's Pick", help_text='Small label in the floating card on the hero image panel.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_tag_value',
            field=models.CharField(default='Blush Cascade', help_text='Main text in the floating card on the hero image panel.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_hero_tag',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Show Hero Tag'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_eyebrow',
            field=models.CharField(default='Curated Selection', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='bestsellers_eyebrow',
            field=models.CharField(default='Most Loved', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='bestsellers_title',
            field=models.CharField(default='Best Sellers', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_eyebrow',
            field=models.CharField(default='Happy Customers', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_title',
            field=models.CharField(default='What they say', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_category_pills',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Category Pills Strip'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_featured_products',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Latest Arrivals Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_why_strip',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Why Us Strip'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_best_sellers',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Best Sellers Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_testimonials',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Testimonials Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='announcement_text',
            field=models.CharField(default='🌸   Free delivery on orders over 200 AED  |  Same-day delivery available  🌸', help_text='Text shown in the top announcement bar. Leave blank to use the dynamic Announcement Bar records.', max_length=400),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_announcement_bar',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Announcement Bar'),
        ),
    ]
