# Generated by Django 5.0 on 2026-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_homepagesettings_exclusive_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='announcement_text',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='bestsellers_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='bestsellers_title',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='exclusive_products',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='featured_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_tag_label',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_tag_value',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_title_em',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_title_line1',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_title_line2',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='onsale_products',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_announcement_bar',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_best_sellers',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_category_pills',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_featured_products',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_hero_tag',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_testimonials',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='show_why_strip',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='testimonials_eyebrow',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='testimonials_title',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='categories_btn_link',
            field=models.CharField(default='/products/categories/', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='categories_btn_text',
            field=models.CharField(default='View All', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='categories_subtitle',
            field=models.TextField(blank=True, default='Explore our comprehensive range of healthcare supplies'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='categories_title',
            field=models.CharField(default='Shop by Category', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_primary_btn_link',
            field=models.CharField(default='/contact/', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_primary_btn_text',
            field=models.CharField(default='Get a Quote', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_secondary_btn_link',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use the global site settings phone number automatically.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_secondary_btn_text',
            field=models.CharField(default='Call Us', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_subtitle',
            field=models.TextField(blank=True, default='Our dedicated team is ready to help you find the right solutions for your facility.'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_title',
            field=models.CharField(default='Need Bulk Orders or Custom Quotes?', max_length=250),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_1_desc',
            field=models.CharField(default='Next-day delivery on orders', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_1_icon',
            field=models.CharField(default='fas fa-shipping-fast', help_text='FontAwesome icon class.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_1_title',
            field=models.CharField(default='Fast Shipping', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_2_desc',
            field=models.CharField(default='ISO, FDA compliant', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_2_icon',
            field=models.CharField(default='fas fa-award', help_text='FontAwesome icon class.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_2_title',
            field=models.CharField(default='Certified Quality', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_3_desc',
            field=models.CharField(default='Expert assistance always', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_3_icon',
            field=models.CharField(default='fas fa-headset', help_text='FontAwesome icon class.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_3_title',
            field=models.CharField(default='24/7 Support', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_4_desc',
            field=models.CharField(default='30-day return policy', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_4_icon',
            field=models.CharField(default='fas fa-undo-alt', help_text='FontAwesome icon class.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='feature_4_title',
            field=models.CharField(default='Easy Returns', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_btn_link',
            field=models.CharField(default='/products/', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_btn_text',
            field=models.CharField(default='View All', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_badge_text',
            field=models.CharField(default='Trusted by 500+ Healthcare Providers', help_text='Small label above the main title.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_stat_1_label',
            field=models.CharField(default='Products', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_stat_1_number',
            field=models.CharField(default='2,500+', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_stat_2_label',
            field=models.CharField(default='Brands', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_stat_2_number',
            field=models.CharField(default='150+', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_stat_3_label',
            field=models.CharField(default='Satisfaction', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_stat_3_number',
            field=models.CharField(default='98%', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_title_html',
            field=models.CharField(default='Equipping Healthcare<br>for the <em>Modern Era</em>', help_text='Main heading of the homepage hero. Supports HTML like <br> and <em>.', max_length=512),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_categories_section',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Categories Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_cta_section',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='CTA Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_featured_section',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Featured Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_features_strip',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Features Strip'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_testimonial_section',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Testimonial Section'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial_author_avatar_initials',
            field=models.CharField(default='JD', help_text='Initials to display in the circular avatar.', max_length=10),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial_author_name',
            field=models.CharField(default='Dr. James Davidson', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial_author_role',
            field=models.CharField(default='Chief of Medicine, Emirates Hospital', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonial_text',
            field=models.TextField(default='Working with 21st Century Healthcare has transformed how we source medical equipment. Their product range, competitive pricing, and exceptional support are unmatched in the industry.'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_subtitle',
            field=models.TextField(blank=True, default='Handpicked essentials for your practice'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_title',
            field=models.CharField(default='Featured Products', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn1_link',
            field=models.CharField(default='/products/categories/', max_length=255, verbose_name='Primary Button Link'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn1_text',
            field=models.CharField(default='Browse Catalog', max_length=100, verbose_name='Primary Button Text'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn2_link',
            field=models.CharField(default='/contact/', max_length=255, verbose_name='Secondary Button Link'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn2_text',
            field=models.CharField(default='Request Quote', max_length=100, verbose_name='Secondary Button Text'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtitle',
            field=models.TextField(default='Cutting-edge medical equipment and supplies, curated for hospitals, clinics, and practices worldwide. Precision, reliability, and care in every product.'),
        ),
    ]
