# Generated by Django 6.0.3 on 2026-06-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_reset_homepagesettings_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='announcement_text',
            field=models.CharField(default='📦 \xa0 Free delivery on qualifying orders \xa0|\xa0 Same-day dispatch available \xa0|\xa0 ISO & FDA certified products \xa0🏥', help_text='Fallback text shown in the top announcement bar. Leave blank to use the dynamic Announcement Bar records (Core → Announcement Bars).', max_length=400),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='bestsellers_eyebrow',
            field=models.CharField(default='Top Picks', help_text='Small eyebrow label above the Best Sellers section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='bestsellers_title',
            field=models.CharField(default='Our Best Sellers', help_text='Heading for the Best Sellers section (maps to hp_bestsellers_title in DesignSettings).', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_eyebrow',
            field=models.CharField(default='New Arrivals', help_text='Small eyebrow label above the Latest Products section title.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_subtitle',
            field=models.TextField(blank=True, default='Discover our newest medical equipment and healthcare supplies.', help_text='Subtitle below the Latest Products heading.'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_title',
            field=models.CharField(default='Latest Products', help_text='Heading for the Latest Products section (maps to hp_latest_products_title in DesignSettings).', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn1_text',
            field=models.CharField(default='Browse Catalog', help_text='Primary hero CTA button label.', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn2_link',
            field=models.CharField(default='/contact/', help_text='URL or path for the secondary hero button.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_btn2_text',
            field=models.CharField(default='Request Quote', help_text='Secondary hero CTA button label.', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_eyebrow',
            field=models.CharField(default='Trusted by 500+ Healthcare Providers', help_text='Badge text above the hero title (only used in alternative hero templates).', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtitle',
            field=models.TextField(default='Cutting-edge medical equipment and supplies, curated for hospitals, clinics, and practices worldwide. Precision, reliability, and care in every product.', help_text='Paragraph below the hero title.'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_tag_label',
            field=models.CharField(default='New Arrival', help_text='Small label in the floating card on the hero panel (only in alternative hero templates).', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_tag_value',
            field=models.CharField(default='Latest Medical Equipment', help_text='Main text in the floating card on the hero panel.', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title_em',
            field=models.CharField(default='Modern Era', help_text='Emphasised/italic word in the hero title.', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title_line1',
            field=models.CharField(default='Equipping Healthcare', help_text='First line of the large hero title.', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title_line2',
            field=models.CharField(default='for the', help_text='Third line of the large hero title.', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_announcement_bar',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='Toggle the slim announcement bar at the very top of every page.', verbose_name='Announcement Bar'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_best_sellers',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='On Sale Now / Best Sellers slider (section 6 in index.html).', verbose_name='Best Sellers / On Sale Section'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_category_pills',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='The 8-icon category icon row below the hero (section 1B in index.html).', verbose_name='Shop by Category Strip'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_featured_products',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='The Latest Products slider (section 4 in index.html).', verbose_name='Latest Products Section'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_hero_tag',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=False, help_text='Not used in the current homepage layout.', verbose_name='Show Hero Tag'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_testimonials',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text='The Testimonials carousel (section 8 in index.html).', verbose_name='Testimonials Section'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_why_strip',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, help_text="The 'Why Choose Us' cards strip (section 7 in index.html).", verbose_name='Why Us Strip'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='testimonials_eyebrow',
            field=models.CharField(default='Client Reviews', help_text='Small eyebrow label above the Testimonials section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='testimonials_title',
            field=models.CharField(default='What Our Customers Say', help_text='Heading for the Testimonials section (maps to hp_testimonials_title in DesignSettings).', max_length=200),
        ),
    ]
