"""
Settings for the JKR project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import sys
import os
import environ
import cloudinary
from pathlib import Path

# =============================================================================
# PATH CONFIGURATION
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================

env = environ.Env(
    DEBUG=(bool, True),
    IS_PRODUCTION=(bool, False),
)

# Load .env.local for development, fall back to .env for production
if os.path.exists(os.path.join(BASE_DIR, ".env.local")):
    environ.Env.read_env(os.path.join(BASE_DIR, ".env.local"), overwrite=True)
else:
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

# =============================================================================
# CORE SECURITY SETTINGS
# =============================================================================

SECRET_KEY = env("SECRET_KEY", default="django-insecure-build-placeholder-key")
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[".creativegradientz.com", ".up.railway.app", "localhost", "127.0.0.1"])
# Check if we are running in production (Railway/Production)
# We check IS_PRODUCTION env var, but also fallback to common production indicators
IS_PRODUCTION = env.bool("IS_PRODUCTION", default=False) or env("DATABASE_URL", default=None) is not None or env("RAILWAY_STATIC_URL", default=None) is not None

ADMIN_URL = env("ADMIN_URL", default="admin/")
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[
    "https://shop.creativegradientz.com",
    "https://ecom.creativegradientz.com",
    "https://admin.creativegradientz.com",
    "https://creativegradientz.com",
    "https://admin-production-dac3.up.railway.app",
    "https://*.up.railway.app",
])

# =============================================================================
# INSTALLED APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    # Admin theme — must come before django.contrib.admin
    "jazzmin",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "cloudinary_storage",
    "django.contrib.staticfiles",
    "cloudinary",

    # Third-party packages
    "ckeditor",
    "ckeditor_uploader",
    "import_export",
    "rest_framework",

    # Project apps
    "accounts",
    "core",
    "products",
    "orders",
    "sliders",
    "pages",
    "contact",
    "blog",
]

# =============================================================================
# AUTHENTICATION
# =============================================================================

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "core:home"
LOGOUT_REDIRECT_URL = "core:home"

# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "core.security_middleware.SecurityShieldMiddleware",  # Bot/Probe blocking
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",  # Content Security Policy protection
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "core.middleware.StripHTMLCommentsMiddleware",
]

# =============================================================================
# SECURITY HARDENING
# =============================================================================

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Silence known third-party warnings that are not yet actionable
SILENCED_SYSTEM_CHECKS = [
    "ckeditor.W001",  # CKEditor 4 EOL — will migrate to CKEditor 5 in a future sprint
]

# --- Content Security Policy (CSP) ---
# This prevents XSS by restricting where resources can be loaded from.
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", "https://ka-f.fontawesome.com")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", "https://js.stripe.com", "https://kit.fontawesome.com", "https://checkout.tabby.ai")
CSP_IMG_SRC = ("'self'", "data:", "https://res.cloudinary.com", "https://*.stripe.com", "https://*.tabby.ai")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://ka-f.fontawesome.com")
CSP_CONNECT_SRC = ("'self'", "https://ka-f.fontawesome.com", "https://api.stripe.com", "https://api.tabby.ai", "https://checkout.tabby.ai")
CSP_FRAME_SRC = ("'self'", "https://js.stripe.com", "https://checkout.tabby.ai")
CSP_OBJECT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)

# Production-only security headers (proxy-aware for Railway / Hostinger)
if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Disable SSL redirect when running manage.py locally
    is_running_locally = any(arg in sys.argv for arg in ["runserver", "dev"])
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not is_running_locally)

    SESSION_COOKIE_SECURE = not is_running_locally
    CSRF_COOKIE_SECURE = not is_running_locally
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CONTENT_TYPE_NOSNIFF = True

    if not is_running_locally:
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
        X_FRAME_OPTIONS = "DENY"
        CSP_UPGRADE_INSECURE_REQUESTS = True

# =============================================================================
# URL & WSGI CONFIGURATION
# =============================================================================

ROOT_URLCONF = "jkr.urls"
WSGI_APPLICATION = "jkr.wsgi.application"

# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Django built-ins
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Custom site-wide context
                "core.context_processors.site_settings",
                "core.context_processors.page_heroes",
                "core.context_processors.admin_dashboard",
                # App-specific context
                "orders.context_processors.cart_count",
                "products.context_processors.categories",
                "products.context_processors.wishlist_data",
            ],
        },
    },
]

# =============================================================================
# DATABASE
# Uses DATABASE_URL (Neon/Supabase) when set, otherwise falls back to SQLite
# =============================================================================

if env("DATABASE_URL", default=None):
    DATABASES = {"default": env.db()}
    # Neon poolers work better with short-lived connections or 0 in some environments
    DATABASES["default"]["CONN_MAX_AGE"] = 0
    
    # Required for Neon/Supabase poolers to avoid InvalidCursorName (server-side cursor) errors
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True

    # Enforce SSL for remote PostgreSQL (Neon / Supabase)
    if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
        DATABASES["default"].setdefault("OPTIONS", {})
        # Merge existing options if any
        DATABASES["default"]["OPTIONS"]["sslmode"] = "require"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =============================================================================
# CACHING
# =============================================================================
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "jkr-unique-snowflake",
    }
}

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =============================================================================
# INTERNATIONALISATION
# =============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Dubai"
USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise options (finders enabled so collectstatic is not required in dev)
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_COMPRESS = False
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

# Storage configuration
if IS_PRODUCTION:
    # Media files (Cloudinary)
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    # Static files (WhiteNoise)
    STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"
    # Ensure MEDIA_URL doesn't interfere with Cloudinary URL generation in some cases
    MEDIA_URL = "https://res.cloudinary.com/%s/" % env("CLOUDINARY_CLOUD_NAME", default="dkhblh1sr")
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
    MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# CKEDITOR RICH-TEXT EDITOR
# =============================================================================

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Full",
        "height": 300,
        "width": "100%",
        "removePlugins": "exportpdf",  # Suppresses unsupported plugin console errors
    },
}

# =============================================================================
# JAZZMIN ADMIN THEME
# =============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "JKR Administration",
    "site_header": "JKR Admin",
    "site_brand": "JKR International",
    "welcome_sign": "Welcome to JKR International Management System",
    "search_model": ["products.Product"],
    "show_ui_builder": False,
    "show_recent_actions": False,
    "actions_sticky": True,
    "edit_id_fields": True,
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "order_with_respect_to": [
        "products", "sliders", "orders", "core", "accounts", "blog", "pages", "contact", "auth",
    ],
    "icons": {
        # Auth & Users
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Store Management
        "products.Product": "fas fa-box",
        "products.Category": "fas fa-tags",
        "products.Collection": "fas fa-layer-group",
        "products.Offer": "fas fa-percent",
        "products.Brand": "fas fa-copyright",
        "products.TrustBadge": "fas fa-shield-alt",
        # Orders & Customers
        "orders.CustomerOrder": "fas fa-shopping-cart",
        "core.Client": "fas fa-users",
        # Content Management
        "blog.Post": "fas fa-file-alt",
        "pages.Page": "fas fa-copy",
        "core.Testimonial": "fas fa-comment-dots",
        # Website Design
        "sliders.HeroSlider": "fas fa-image",
        "sliders.PromoBanner": "fas fa-ad",
        "core.AnnouncementBar": "fas fa-bullhorn",
        "core.DesignSettings": "fas fa-paint-brush",
        # Communication
        "contact.ContactFormSubmission": "fas fa-envelope",
        "contact.NewsletterSubscriber": "fas fa-paper-plane",
        # Settings
        "core.SiteSettings": "fas fa-cog",
        "core.StoreLocation": "fas fa-map-marker-alt",
        "core.SocialPost": "fas fa-share-alt",
    },
    "custom_css": "admin/css/admin_premium.css",
    "custom_js": "admin/js/admin_ux.js",
}

# =============================================================================
# CLOUDINARY (Media CDN in Production)
# =============================================================================

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": env("CLOUDINARY_CLOUD_NAME", default="dltest"),
    "API_KEY": env("CLOUDINARY_API_KEY", default="1234567"),
    "API_SECRET": env("CLOUDINARY_API_SECRET", default="secretkey"),
}

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
    api_key=CLOUDINARY_STORAGE["API_KEY"],
    api_secret=CLOUDINARY_STORAGE["API_SECRET"],
)

# =============================================================================
# PAYMENT GATEWAYS
# =============================================================================

# --- Stripe ---
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="sk_test_12345")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="pk_test_12345")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default=None)

# --- Tabby (Buy Now, Pay Later) ---
TABBY_API_KEY = env("TABBY_API_KEY", default="")
TABBY_SECRET_KEY = env("TABBY_SECRET_KEY", default="")
TABBY_MERCHANT_CODE = env("TABBY_MERCHANT_CODE", default="")
TABBY_TEST_MODE = env.bool("TABBY_TEST_MODE", default=True)

# --- Tamara (Buy Now, Pay Later) ---
TAMARA_API_KEY = env("TAMARA_API_KEY", default="")
TAMARA_API_TOKEN = env("TAMARA_API_TOKEN", default="")
TAMARA_MERCHANT_ID = env("TAMARA_MERCHANT_ID", default="")
TAMARA_TEST_MODE = env.bool("TAMARA_TEST_MODE", default=True)

# =============================================================================
# EMAIL
# =============================================================================

SITE_URL = env("SITE_URL", default="http://localhost:8000")
CURRENCY = env("CURRENCY", default="AED")

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env("EMAIL_PORT", cast=int, default=587)
EMAIL_USE_TLS = env("EMAIL_USE_TLS", cast=bool, default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default=env("EMAIL_HOST_USER", default="notifications@jkrinternational.com"),
)

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# =============================================================================
# SUPABASE AUTH
# =============================================================================
SUPABASE_URL = env("SUPABASE_URL", default="")
SUPABASE_KEY = env("SUPABASE_KEY", default="")

# =============================================================================
# AI SERVICES (KIMI)
# =============================================================================
NVIDIA_KIMI_API_KEY = env("NVIDIA_KIMI_API_KEY", default=None)
KIMI_MODEL = env("KIMI_MODEL", default="moonshotai/kimi-k2.6")

NVIDIA_MINIMAX_API_KEY = env("NVIDIA_MINIMAX_API_KEY", default=None)
MINIMAX_MODEL = env("MINIMAX_MODEL", default="minimaxai/minimax-m2.7")

NVIDIA_GLM_API_KEY = env("NVIDIA_GLM_API_KEY", default=None)
GLM_MODEL = env("GLM_MODEL", default="z-ai/glm-5.1")

