"""
Settings for the JKR project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import sys
import os
import environ
import cloudinary
from pathlib import Path
import core.monkeypatch_django

# =============================================================================
# PATH CONFIGURATION
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Detect if we are running locally (development/management tasks)
IS_RUNNING_LOCALLY = any(arg in sys.argv for arg in ["runserver", "dev", "shell", "check", "migrate", "makemigrations", "test"])
HAS_ENV_LOCAL = os.path.exists(os.path.join(BASE_DIR, ".env.local"))

# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================

env = environ.Env(
    DEBUG=(bool, True),
    IS_PRODUCTION=(bool, False),
)

# Load .env.local for development, fall back to .env for production
if HAS_ENV_LOCAL:
    environ.Env.read_env(os.path.join(BASE_DIR, ".env.local"), overwrite=True)
else:
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

# =============================================================================
# CORE SECURITY SETTINGS
# =============================================================================

SECRET_KEY = env("SECRET_KEY", default="django-insecure-build-placeholder-key")

# Dynamically resolve DEBUG and IS_PRODUCTION for smooth local development
if IS_RUNNING_LOCALLY:
    if HAS_ENV_LOCAL:
        DEBUG = env.bool("DEBUG", default=True)
        IS_PRODUCTION = env.bool("IS_PRODUCTION", default=False)
    else:
        DEBUG = True
        IS_PRODUCTION = False
else:
    DEBUG = env.bool("DEBUG", default=False)
    IS_PRODUCTION = env.bool("IS_PRODUCTION", default=True)

# ALLOWED_HOSTS — includes Railway wildcard and custom domain
_default_allowed_hosts = [
    "shop.creativegradientz.com",
    "ecom.creativegradientz.com",
    "admin.creativegradientz.com",
    "creativegradientz.com",
    ".up.railway.app",
    "localhost",
    "127.0.0.1",
]
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=_default_allowed_hosts)

# Force inclusion of local host identifiers during local execution
if IS_RUNNING_LOCALLY:
    for host in ["localhost", "127.0.0.1", "[::1]", "*"]:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

ADMIN_URL = env("ADMIN_URL", default="admin/")

# CSRF_TRUSTED_ORIGINS — must include full https:// scheme for every domain
_default_csrf_origins = [
    "https://shop.creativegradientz.com",
    "https://ecom.creativegradientz.com",
    "https://admin.creativegradientz.com",
    "https://creativegradientz.com",
    "https://*.up.railway.app",
]
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=_default_csrf_origins)

# =============================================================================
# INSTALLED APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    # Admin theme — must come before django.contrib.admin
    "jazzmin",

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "cloudinary_storage",
    "django.contrib.staticfiles",
    "cloudinary",

    # Third-party packages
    "ckeditor",
    "ckeditor_uploader",
    "import_export",
    "rest_framework",

    # Project apps
    "subscriptions.apps.SubscriptionsConfig",
    "accounts",
    "core",
    "products",
    "orders",
    "sliders",
    "pages",
    "contact",
    "blog",
]

# =============================================================================
# AUTHENTICATION
# =============================================================================

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "core:home"
LOGOUT_REDIRECT_URL = "core:home"

# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "core.security_middleware.SecurityShieldMiddleware",  # Bot/Probe blocking
    "core.middleware.NoCacheMiddleware",  # Prevent browser caching of HTML
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",  # Content Security Policy protection
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "core.middleware.StripHTMLCommentsMiddleware",
]

# =============================================================================
# SECURITY HARDENING
# =============================================================================

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"

# Silence known third-party warnings that are not yet actionable
SILENCED_SYSTEM_CHECKS = [
    "ckeditor.W001",  # CKEditor 4 EOL — will migrate to CKEditor 5 in a future sprint
]

# --- Content Security Policy (CSP) ---
# This prevents XSS by restricting where resources can be loaded from.
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", "https://ka-f.fontawesome.com")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", "https://js.stripe.com", "https://kit.fontawesome.com", "https://checkout.tabby.ai")
CSP_IMG_SRC = ("'self'", "data:", "https://res.cloudinary.com", "https://*.stripe.com", "https://*.tabby.ai")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://ka-f.fontawesome.com")
CSP_CONNECT_SRC = ("'self'", "https://ka-f.fontawesome.com", "https://api.stripe.com", "https://api.tabby.ai", "https://checkout.tabby.ai")
CSP_FRAME_SRC = ("'self'", "https://js.stripe.com", "https://checkout.tabby.ai")
CSP_OBJECT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)

# Production-only security headers (proxy-aware for Railway / Hostinger)
if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Disable SSL redirect when running manage.py locally
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not IS_RUNNING_LOCALLY)

    SESSION_COOKIE_SECURE = not IS_RUNNING_LOCALLY
    CSRF_COOKIE_SECURE = not IS_RUNNING_LOCALLY
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CONTENT_TYPE_NOSNIFF = True

    if not IS_RUNNING_LOCALLY:
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
        X_FRAME_OPTIONS = "DENY"
        CSP_UPGRADE_INSECURE_REQUESTS = True

# =============================================================================
# URL & WSGI CONFIGURATION
# =============================================================================

ROOT_URLCONF = "jkr.urls"
WSGI_APPLICATION = "jkr.wsgi.application"

# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Django built-ins
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Custom site-wide context
                "core.context_processors.site_settings",
                "core.context_processors.page_heroes",
                "core.context_processors.admin_dashboard",
                # App-specific context
                "orders.context_processors.cart_count",
                "products.context_processors.categories",
                "products.context_processors.wishlist_data",
            ],
        },
    },
]

# =============================================================================
# DATABASE
# Uses DATABASE_URL (Neon/Supabase) when set, otherwise falls back to SQLite
# =============================================================================

if env("DATABASE_URL", default=None):
    DATABASES = {"default": env.db()}
    # Neon poolers work better with short-lived connections or 0 in some environments
    DATABASES["default"]["CONN_MAX_AGE"] = 0
    
    # Required for Neon/Supabase poolers to avoid InvalidCursorName (server-side cursor) errors
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True

    # Enforce SSL for remote PostgreSQL (Neon / Supabase)
    if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
        DATABASES["default"].setdefault("OPTIONS", {})
        # Merge existing options if any
        DATABASES["default"]["OPTIONS"]["sslmode"] = "require"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =============================================================================
# CACHING
# =============================================================================
REDIS_URL = env("REDIS_URL", default=None)

if REDIS_URL:
    try:
        import django_redis  # noqa: F401 - verify package is installed
        CACHES = {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": REDIS_URL,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "SOCKET_CONNECT_TIMEOUT": 5,
                    "SOCKET_TIMEOUT": 5,
                    "IGNORE_EXCEPTIONS": True,  # Don't crash if Redis is unavailable
                },
                "KEY_PREFIX": "jkr",
                "TIMEOUT": 300,
            }
        }
    except ImportError:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "jkr-fallback",
            }
        }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "jkr-unique-snowflake",
        }
    }

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =============================================================================
# INTERNATIONALISATION
# =============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Dubai"
USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise options (finders enabled so collectstatic is not required in dev)
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_COMPRESS = False
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

# -----------------------------------------------------------------------------
# STATIC & MEDIA FILES CONFIGURATION
# -----------------------------------------------------------------------------

# For local dev, serve from local filesystem
# For production (IS_PRODUCTION), we serve static via WhiteNoise and media via Cloudinary

if IS_PRODUCTION:
    # Use standard Cloudinary storage for media
    MEDIA_STORAGE_BACKEND = "cloudinary_storage.storage.MediaCloudinaryStorage"
    # Use WhiteNoise for static files
    STATIC_STORAGE_BACKEND = "whitenoise.storage.CompressedManifestStaticFilesStorage"
else:
    MEDIA_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"
    STATIC_STORAGE_BACKEND = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Fallbacks for libraries that still check these legacy settings (like django-cloudinary-storage)
STATICFILES_STORAGE = STATIC_STORAGE_BACKEND
DEFAULT_FILE_STORAGE = MEDIA_STORAGE_BACKEND

# Django 4.2+ native way to configure storages
STORAGES = {
    "default": {
        "BACKEND": MEDIA_STORAGE_BACKEND,
    },
    "staticfiles": {
        "BACKEND": STATIC_STORAGE_BACKEND,
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# CKEDITOR RICH-TEXT EDITOR
# =============================================================================

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Full",
        "height": 300,
        "width": "100%",
        "removePlugins": "exportpdf",  # Suppresses unsupported plugin console errors
    },
}

# =============================================================================
# JAZZMIN ADMIN THEME
# =============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "JKR Administration",
    "site_header": "JKR Admin",
    "site_brand": "JKR International",
    "site_logo": None,
    "login_logo": None,
    "welcome_sign": "Welcome to JKR International Management System",
    "copyright": "JKR International",
    "search_model": ["products.Product"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "products", "sliders", "orders", "core", "accounts", "blog", "pages", "contact", "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "products.Product": "fas fa-box",
        "products.Category": "fas fa-tags",
        "products.Collection": "fas fa-layer-group",
        "products.Offer": "fas fa-percent",
        "products.Brand": "fas fa-copyright",
        "products.TrustBadge": "fas fa-shield-alt",
        "orders.CustomerOrder": "fas fa-shopping-cart",
        "core.Client": "fas fa-users",
        "blog.Post": "fas fa-file-alt",
        "pages.Page": "fas fa-copy",
        "core.Testimonial": "fas fa-comment-dots",
        "sliders.HeroSlider": "fas fa-image",
        "sliders.PromoBanner": "fas fa-ad",
        "core.AnnouncementBar": "fas fa-bullhorn",
        "core.DesignSettings": "fas fa-paint-brush",
        "contact.ContactFormSubmission": "fas fa-envelope",
        "contact.NewsletterSubscriber": "fas fa-paper-plane",
        "core.SiteSettings": "fas fa-cog",
        "core.StoreLocation": "fas fa-map-marker-alt",
        "core.SocialPost": "fas fa-share-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/css/admin_premium.css",
    "custom_js": "admin/js/admin_ux.js",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "show_recent_actions": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# =============================================================================
# CLOUDINARY (Media CDN in Production)
# =============================================================================

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": env("CLOUDINARY_CLOUD_NAME", default="dltest"),
    "API_KEY": env("CLOUDINARY_API_KEY", default="1234567"),
    "API_SECRET": env("CLOUDINARY_API_SECRET", default="secretkey"),
}

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
    api_key=CLOUDINARY_STORAGE["API_KEY"],
    api_secret=CLOUDINARY_STORAGE["API_SECRET"],
)

# =============================================================================
# PAYMENT GATEWAYS
# =============================================================================

# --- Stripe ---
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="sk_test_12345")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="pk_test_12345")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default=None)

# --- Tabby (Buy Now, Pay Later) ---
TABBY_API_KEY = env("TABBY_API_KEY", default="")
TABBY_SECRET_KEY = env("TABBY_SECRET_KEY", default="")
TABBY_MERCHANT_CODE = env("TABBY_MERCHANT_CODE", default="")
TABBY_TEST_MODE = env.bool("TABBY_TEST_MODE", default=True)

# --- Tamara (Buy Now, Pay Later) ---
TAMARA_API_KEY = env("TAMARA_API_KEY", default="")
TAMARA_API_TOKEN = env("TAMARA_API_TOKEN", default="")
TAMARA_MERCHANT_ID = env("TAMARA_MERCHANT_ID", default="")
TAMARA_TEST_MODE = env.bool("TAMARA_TEST_MODE", default=True)

# =============================================================================
# EMAIL
# =============================================================================

SITE_URL = env("SITE_URL", default="http://localhost:8000")
CURRENCY = env("CURRENCY", default="AED")

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env("EMAIL_PORT", cast=int, default=587)
EMAIL_USE_TLS = env("EMAIL_USE_TLS", cast=bool, default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default=env("EMAIL_HOST_USER", default="notifications@jkrinternational.com"),
)

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.template": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "orders": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "products": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist (Only attempt if local)
if not IS_PRODUCTION:
    try:
        logs_dir = BASE_DIR / "logs"
        if not logs_dir.exists():
            logs_dir.mkdir(mode=0o755, exist_ok=True)
    except Exception:
        pass



# =============================================================================
# SUPABASE AUTH
# =============================================================================
SUPABASE_URL = env("SUPABASE_URL", default="")
SUPABASE_KEY = env("SUPABASE_KEY", default="")
