# Generated by Django 6.0.3 on 2026-05-25 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_customerorder_coupon_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['payment_status', 'status'], name='order_payment_status'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['email', '-created_at'], name='order_email_created'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['stripe_session_id'], name='order_stripe_session'),
        ),
    ]
