# Generated by Django 6.0.3 on 2026-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_brand_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], db_index=True, default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], db_index=True, default=False, verbose_name='Homepage Display'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'quantity', 'shipping_status'], name='product_active_qty_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'show_on_homepage'], name='product_active_homepage'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'quantity'], name='product_cat_active_qty'),
        ),
    ]
