# Generated by Django 6.0.3 on 2026-06-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_alter_product_created_at_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_homepage',
        ),
        migrations.AddField(
            model_name='product',
            name='exclusive_products',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Exclusive Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale_now',
            field=models.BooleanField(db_index=True, default=False, verbose_name='On Sale Now'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'exclusive_products'], name='product_active_excl'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'on_sale_now'], name='product_active_onsale'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_on_homepage',
        ),
    ]
